const endpoint = process.env.FREEPLANE_MCP_URL || 'http://127.0.0.1:6298/';
const token = process.env.FREEPLANE_MCP_TOKEN;
if (!token) throw new Error('Set FREEPLANE_MCP_TOKEN before running this script.');
let requestId=1;
async function mcp(method,params){const r=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:requestId++,method,params})});const b=await r.text();if(!r.ok)throw Error(`${method}: ${r.status} ${b}`);const p=JSON.parse(b);if(p.error)throw Error(JSON.stringify(p.error));return p.result;}
const tool=(name,args)=>mcp('tools/call',{name,arguments:args});const c=(text,details)=>details?{text,details}:{text};
function flatten(branch){const nodes=[];function v(x,p){const i=nodes.length;nodes.push({index:i,parentIndex:p,content:c(x.text,x.details),...(x.children?.length?{foldingState:'UNFOLD'}:{})});for(const y of x.children||[])v(y,i);}v(branch,-1);return nodes;}
const chapter11={text:'第11章 未来信息综合技术',details:'依据教材第11章（369-403页）整理：信息物理系统、人工智能、机器人、边缘计算、数字孪生、云计算与大数据。',children:[
 {text:'11.1 信息物理系统 CPS',details:'CPS 通过感知、计算、通信和控制融合，使物理空间与信息空间中的人、机、物、环境和信息实时映射、交互与协同。',children:[
  {text:'11.1.1 概念与本质',details:'CPS 是控制系统和嵌入式系统的扩展，核心是数据自动流动形成“状态感知→实时分析→科学决策→精准执行”的闭环。',children:[{text:'来源',details:'术语最早由 NASA 于 1992 年提出，2006 年相关学术研讨进一步系统阐述。'},{text:'解决问题',details:'突破传统单点嵌入式方案，融合计算、感知、通信、控制、云计算和智能技术，应对工业系统复杂性与不确定性。'},{text:'最终目标',details:'按需响应、快速迭代、动态优化资源配置，提高生产制造和应用服务效率。'}]},
  {text:'11.1.2 CPS 实现',details:'体系由单元级、系统级和 SoS 级逐级组合扩展。',children:[{text:'单元级 CPS',details:'不可分割的最小单元，完成对物理实体/环境感知、计算分析、控制执行和对外通信；智能部件、工业机器人和智能机床都可属于此级。',children:[{text:'能力',details:'可感知、可计算、可交互、可延展、自决策。'}]},{text:'系统级 CPS',details:'多个单元通过工业现场总线、工业以太网等互联，实现互联互通、互操作、即插即用、边缘网关、数据互操作、协同控制、监视诊断。'},{text:'SoS 级 CPS',details:'多个系统级 CPS 有机组合，面向车间、工厂和跨系统运营，实现数据汇聚、融合、分布式计算、大数据分析、数据服务和运营优化。'},{text:'技术体系',details:'总体技术（架构、异构集成、安全、验证）、支撑技术（感知、嵌入式、数据库、交互、中间件、SDN、IoT、大数据）、核心技术（虚实融合、智能装备、MBD、数字孪生、现场总线、工业软件）。'},{text:'四大要素',details:'一硬：感知与自动控制；一软：工业软件；一网：工业网络；一平台：工业云和智能服务平台。'},{text:'虚实融合控制',details:'通过“感知—分析—决策—执行”循环，包含嵌入控制、虚体控制、集控控制和目标控制。'}]},
  {text:'11.1.3 建设与应用',details:'CPS 应用覆盖智能设计、智能生产、智能服务和智能应用。',children:[{text:'智能设计',details:'利用虚拟模型和仿真预演产品、工艺和工厂设计，提前发现问题，缩短设计到生产周期。'},{text:'智能生产',details:'设备互联、实时感知、协同控制和生产过程优化，提高资源利用率和柔性。'},{text:'智能服务',details:'基于产品运行数据提供远程监测、预测维护、个性化服务和全生命周期管理。'},{text:'智能应用',details:'面向智慧工厂、智能交通、能源、医疗和城市等复杂系统。'}]}
 ]},
 {text:'11.2 人工智能技术',details:'人工智能研究用机器模拟、延伸和扩展人的感知、学习、推理、决策和行动能力。',children:[
  {text:'11.2.1 人工智能概念',details:'AI 是计算机科学与数学、心理学、神经科学、语言学等交叉形成的技术体系。',children:[{text:'弱人工智能',details:'针对特定任务表现出智能，如识别、推荐、翻译和棋类系统，不具备通用认知能力。'},{text:'强人工智能',details:'理论上具备跨领域理解、学习、推理和自主决策能力，接近或达到人类通用智能，当前仍属发展目标。'},{text:'能力维度',details:'感知、表示、学习、推理、规划、决策、行动、交互和自适应。'}]},
  {text:'11.2.2 发展历程',details:'经历符号主义/推理、专家系统、统计学习、深度学习和大模型等阶段。',children:[{text:'早期探索',details:'以逻辑、搜索、定理证明和博弈为主，强调符号表示和规则推理。'},{text:'专家系统时期',details:'知识库加推理机模拟领域专家，面临知识获取瓶颈和维护困难。'},{text:'机器学习时期',details:'从数据学习统计规律，支持分类、回归、聚类和推荐。'},{text:'深度学习时期',details:'多层神经网络自动学习特征，在视觉、语音和自然语言任务中突破。'},{text:'大模型阶段',details:'通过大规模数据和参数预训练获得通用表示，再以提示、微调和工具调用适配多任务。'}]},
  {text:'11.2.3 人工智能关键技术',details:'关键技术覆盖语言、视觉、知识、交互、机器人和学习。',children:[{text:'自然语言处理 NLP',details:'研究机器对人类语言的理解、生成、翻译、问答、信息抽取和对话。',children:[{text:'典型任务',details:'分词、词性标注、实体识别、情感分析、机器翻译、文本生成和语音语言交互。'},{text:'主要难点',details:'语义歧义、上下文、知识时效、事实性、偏见和可解释性。'}]},{text:'计算机视觉',details:'从图像和视频中提取目标、场景、动作和语义信息，应用于检测、识别、分割、跟踪和三维重建。'},{text:'知识图谱',details:'以实体、属性、关系和事件组织结构化知识，支持查询、推理、问答、推荐和数据融合。'},{text:'人机交互 HCI',details:'研究人与系统通过视觉、语音、触觉、手势和自然语言协同的方式，强调可用性、反馈和安全。'},{text:'机器人智能',details:'感知环境、定位建图、规划、控制和自主执行的综合能力。'},{text:'机器学习',details:'从数据和经验中学习模型。',children:[{text:'监督学习',details:'使用带标签样本学习分类或回归映射。'},{text:'无监督学习',details:'从无标签数据发现聚类、结构和分布。'},{text:'强化学习',details:'通过与环境交互获得奖励，学习策略和决策。'},{text:'深度学习',details:'用多层神经网络自动学习表示，适合复杂高维数据。'},{text:'工程流程',details:'数据采集→清洗标注→特征/表示→训练→验证→部署→监控和再训练。'}]}
 ]},
 {text:'11.3 机器人技术',details:'机器人是集机械、感知、控制、计算、通信和人工智能于一体的可编程自动化系统。',children:[
  {text:'11.3.1 机器人概念',details:'机器人能够感知环境、执行动作并在一定自主程度下完成任务；不仅是机械臂，也包括软件机器人和智能服务平台。'},
  {text:'11.3.2 定义与发展',details:'从程序控制、示教再现发展到具备环境感知、自主规划、协同学习和场景适应的智能机器人。',children:[{text:'发展阶段',details:'工业自动化→感知与控制融合→服务机器人→云边端协同和智能机器人。'},{text:'核心变化',details:'从固定、重复、封闭环境转向开放、协作、柔性和自主环境。'}]},
  {text:'11.3.3 机器人4.0核心技术',details:'机器人4.0强调网络化、智能化、平台化和持续演化。',children:[{text:'云-边-端无缝协同',details:'云提供模型、知识和算力；边缘提供低时延处理；端侧完成实时感知与控制。'},{text:'持续学习与协同学习',details:'机器人根据运行数据持续改进，并通过群体共享经验提升整体能力。'},{text:'知识图谱',details:'组织对象、任务、环境和操作知识，支持推理、问答、规划和迁移。'},{text:'场景自适应',details:'根据环境、任务、用户和风险动态调整感知、规划、控制和交互策略。'},{text:'数据安全',details:'保护机器人身份、控制指令、传感数据、模型和云边通信，防止劫持与隐私泄露。'}]},
  {text:'11.3.4 机器人分类',details:'可按智能程度、应用领域和结构分类。',children:[{text:'按智能程度',details:'操作机器人、程序机器人、示教再现机器人、智能机器人、综合机器人。'},{text:'按应用领域',details:'工业机器人、服务机器人、特殊领域机器人。'},{text:'工业机器人',details:'用于搬运、焊接、装配、喷涂、加工和检测等工业流程。'},{text:'服务机器人',details:'面向家庭、医疗、教育、物流、客服和公共服务。'},{text:'特殊领域机器人',details:'用于军事、深海、太空、核工业、救援和危险环境。'}]}
 ]},
 {text:'11.4 边缘计算',details:'边缘计算把计算、存储、网络和智能服务部署到靠近数据源和用户的网络边缘，减少时延和回传压力。',children:[
  {text:'11.4.1 概念',details:'边缘位于云中心与终端之间，可是网关、基站、边缘服务器、工业控制器或现场设备。'},
  {text:'11.4.2 定义视角',details:'不同组织强调分布式计算、网络边缘节点、服务部署位置和云边端协同，但共同点是靠近数据源处理。',children:[{text:'ECC 视角',details:'在靠近数据源或用户的网络边缘提供计算、存储和网络服务。'},{text:'OpenStack 视角',details:'将云能力扩展到边缘节点，支持边缘基础设施管理和应用部署。'},{text:'ISO/IEC 视角',details:'面向网络边缘的分布式计算能力，支持低时延、位置感知和本地自治。'}]},
  {text:'11.4.3 边缘计算特点',details:'具有低时延、位置感知、带宽节省、数据本地化、隐私保护、异构性、分布式自治和移动性。',children:[{text:'低时延',details:'数据在本地或近端处理，适合控制、交互和实时分析。'},{text:'带宽节省',details:'过滤、聚合和压缩后再上传云端，降低回传流量。'},{text:'本地自治',details:'云不可达时仍可保持关键功能和业务连续性。'},{text:'异构与运维挑战',details:'节点资源、网络、系统和安全能力差异大，需要统一编排、监控、升级和策略管理。'}]},
  {text:'11.4.4 边云协同',details:'云负责全局资源、模型训练、长期存储和复杂分析，边缘负责实时推理、数据预处理和本地控制，端负责采集和执行。',children:[{text:'协同内容',details:'任务卸载、模型下发、数据分层、策略同步、服务迁移和故障切换。'},{text:'协同原则',details:'实时闭环尽量在边缘，跨区域全局分析放在云端，端侧优先保护隐私和低功耗。'}]},
  {text:'11.4.5 边缘安全',details:'边缘节点暴露在现场和多租户环境，需保护设备、平台、应用、数据、网络和运维链路。',children:[{text:'设备与身份',details:'可信启动、设备认证、密钥管理、固件签名和安全更新。'},{text:'数据与通信',details:'传输加密、访问控制、隐私保护、数据最小化和本地隔离。'},{text:'平台与应用',details:'容器隔离、漏洞修复、最小权限、运行时监控、入侵检测和安全审计。'}]},
  {text:'11.4.6 应用场合',details:'智慧园区、云游戏/安卓云、视频监控和工业物联网等。',children:[{text:'智慧园区',details:'本地处理门禁、能耗、视频和环境数据，提供快速联动。'},{text:'云游戏与安卓云',details:'边缘节点就近渲染和编码，降低交互时延。'},{text:'视频监控',details:'边缘完成目标检测、筛选和告警，避免大量原始视频回传。'},{text:'工业物联网',details:'边缘网关连接异构设备，执行实时控制、协议转换和预测维护。'}]}
 ]},
 {text:'11.5 数字孪生体',details:'数字孪生是物理对象、过程或系统在数字空间的动态映射，通过数据和模型实现监测、仿真、预测、优化和闭环控制。',children:[
  {text:'11.5.1 发展历程',details:'从产品全生命周期数字模型、虚拟样机发展到实时数据驱动的数字孪生，再扩展到车间、城市和复杂系统。',children:[{text:'早期思想',details:'用数字模型描述物理对象，服务设计、仿真和维护。'},{text:'实时孪生',details:'传感器和网络使物理实体状态持续映射到数字空间。'},{text:'系统级孪生',details:'多个对象和过程组成系统孪生，支持跨层级分析和运营优化。'}]},
  {text:'11.5.2 定义与特征',details:'数字孪生由物理实体、虚拟实体、连接、数据和服务组成。',children:[{text:'映射与同步',details:'物理实体状态实时或准实时同步到虚拟模型，虚拟分析结果可反馈物理实体。'},{text:'多模型融合',details:'融合几何、机理、行为、规则、数据驱动模型和业务知识。'},{text:'全生命周期',details:'覆盖设计、制造、运行、维护、改造和退役。'},{text:'闭环服务',details:'监测→分析→预测→决策→控制/优化，持续提高对象性能。'}]},
  {text:'11.5.3 关键技术',details:'建模、仿真及数据、连接和平台技术共同支撑数字孪生。',children:[{text:'建模',details:'建立几何、物理、行为、规则和数据模型，统一标识、语义和接口。'},{text:'仿真',details:'用离散事件、连续系统、有限元、系统动力学和多物理场仿真预测状态和方案效果。'},{text:'数据采集与融合',details:'传感器、工业协议、时序数据、历史数据和外部数据的采集、清洗、对齐和融合。'},{text:'连接与交互',details:'物联网、边缘计算、可视化、AR/VR、实时通信和模型同步。'},{text:'智能分析',details:'机器学习、异常检测、预测维护、优化和决策支持。'},{text:'平台治理',details:'模型版本、数据质量、权限、安全、可追溯性和服务编排。'}]},
  {text:'11.5.4 应用',details:'数字孪生应用于制造、产业、城市和战场等领域。',children:[{text:'智能制造',details:'产品设计验证、产线仿真、设备预测维护、工艺优化和质量追溯。'},{text:'产业运营',details:'能源、交通、建筑和供应链的状态监测、资源调度和全生命周期管理。'},{text:'智慧城市',details:'城市基础设施、交通、环境、应急和公共服务的综合仿真与治理。'},{text:'战场/国防',details:'装备状态、任务推演、战场态势和后勤保障的动态建模。'}]}
 ]},
 {text:'11.6 云计算和大数据',details:'云计算提供弹性、按需和服务化计算资源；大数据面向海量、快速、多样和高价值数据进行采集、存储、处理和分析。',children:[
  {text:'11.6.1 云计算',details:'通过网络以服务方式提供可配置计算资源池，支持快速申请、弹性伸缩、按量使用和自动化管理。',children:[{text:'相关概念',details:'虚拟化、资源池、弹性、服务化、按需自助、共享、多租户、计量和自动化编排。'},{text:'IaaS',details:'提供虚拟机、存储、网络等基础资源，用户管理操作系统和应用。'},{text:'PaaS',details:'提供运行时、中间件、数据库、开发和部署平台，用户聚焦应用。'},{text:'SaaS',details:'以完整软件服务交付，用户通过浏览器/API 使用，不管理底层基础设施。'},{text:'部署模式',details:'公有云、私有云、社区云、混合云；选择取决于控制、合规、成本和弹性。'},{text:'发展历程',details:'从分布式计算、网格计算、虚拟化和效用计算演进到云原生、容器、Serverless 和多云。'},{text:'关键挑战',details:'安全、隐私、可靠性、数据迁移、供应商锁定、网络依赖、资源隔离和成本治理。'}]},
  {text:'11.6.2 大数据',details:'大数据关注无法用传统工具在可接受时间内采集、存储、管理和分析的数据集合及其价值。',children:[{text:'定义与 5V',details:'Volume 大量、Velocity 高速、Variety 多样、Value 价值、Veracity 真实性。'},{text:'研究内容',details:'数据采集与清洗、分布式存储、批处理/流处理、数据管理、分析挖掘、可视化、治理和安全。'},{text:'技术体系',details:'分布式文件系统、NoSQL、数据仓库、MapReduce、流计算、内存计算、机器学习和数据湖。'},{text:'应用领域',details:'金融风控、互联网推荐、工业制造、医疗健康、交通、政府治理、能源和科学研究。'},{text:'大数据价值链',details:'采集→传输→存储→治理→计算→分析→决策/服务→反馈。'},{text:'安全与治理',details:'数据分类分级、质量、血缘、权限、脱敏、加密、隐私、合规和生命周期管理。'}]}
 ]},
]};
const selectionResult=await tool('getSelectedMapAndNodeIdentifiers',{request:{selectionCollectionMode:'SINGLE'}});const selection=JSON.parse(selectionResult.content[0].text);const mapIdentifier=selection.mapIdentifier;const anchorNodeIdentifier=process.env.FREEPLANE_ROOT_NODE_ID||selection.rootNodeIdentifier;let chapterNodeIdentifier=process.env.FREEPLANE_CHAPTER11_NODE_ID;
if(!chapterNodeIdentifier){await tool('createNodes',{request:{mapIdentifier,userSummary:'创建第11章详细思维导图',anchorPlacement:{anchorNodeIdentifier,placementMode:'LAST_CHILD'},nodes:[{index:0,parentIndex:-1,content:c(chapter11.text,chapter11.details),foldingState:'UNFOLD'}]}});const result=await tool('searchNodes',{request:{mapIdentifier,queryText:chapter11.text,matchingMode:'EQUALS',caseSensitivity:'CASE_SENSITIVE',limit:20}});const payload=JSON.parse(result.content[0].text);const matches=payload.items||payload.nodes||payload.results||[];chapterNodeIdentifier=matches.at(-1)?.nodeIdentifier;if(!chapterNodeIdentifier)throw Error('Cannot locate chapter 11 root');}for(const branch of chapter11.children)await tool('createNodes',{request:{mapIdentifier,userSummary:`导入${branch.text}`,anchorPlacement:{anchorNodeIdentifier:chapterNodeIdentifier,placementMode:'LAST_CHILD'},nodes:flatten(branch)}});console.log(JSON.stringify({mapIdentifier,chapterNodeIdentifier,chapter:chapter11.text},null,2));
